name: iOS

on:
  push:
    branches: [master]
  pull_request:
    branches: '*'

jobs:
  lint:
    name: Lint with SwiftLint
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: SwiftLint report
        run: swiftlint lint --reporter github-actions-logging --config "FlipperZero/.swiftlint.yml"

  build:
    name: Build and Test using iPhone 11 simulator
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Xcode version selection
        run: sudo xcode-select --switch /Applications/Xcode_12.4.app
      - name: Build and Test
        run: xcodebuild test -project ./FlipperZero/FlipperZero.xcodeproj -scheme 'FlipperZero(iOS)' -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.4' -enableCodeCoverage YES build test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
