name: iOS

on:
  push:
    branches: [master]
  pull_request:
    branches: '*'

jobs:
  lint:
    name: Lint with SwiftLint
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: SwiftLint report
        run: swiftlint lint --reporter github-actions-logging

  build:
    name: Build and Test using iPhone 12 simulator
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Xcode version selection
        run: sudo xcode-select -s /Applications/Xcode_13.2.app
      - name: Build and Test
        run: xcodebuild test -project ./Flipper/Flipper.xcodeproj -scheme 'Flipper(iOS)' -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.2' -enableCodeCoverage YES build test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
